Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/precise32"
	config.vm.network :forwarded_port, host: 3000, guest: 3000

	config.vm.provision :shell, :path => "shell/prereqs.sh", :args => "puppet"

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "puppet/manifests"
		puppet.manifest_file  = "init.pp"
	end
	config.vm.synced_folder "C:\\users\\mcnawi11\\agreemates", "/home"
	config.vm.provision :shell,
    inline: "wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh"
	
	config.vm.provision :shell, :path => "shell/install_agreemates.sh"
end
