Vagrant.configure("2") do |config|
	config.vm.box = "hashicorp/precise32"
	config.vm.network :forwarded_port, host: 5000, guest: 80

	config.vm.provision :shell, :path => "shell/prereqs.sh", :args => "puppet"

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "puppet/manifests"
		puppet.manifest_file  = "init.pp"
	end

	config.vm.provision :shell, :path => "shell/install_agreemates.sh"
end
